version: '3.7'

services:
  tatsuya_db_container:
    image: mysql:8.0
    container_name: tatsuya_db_container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
